name: GitHub pages
on: [push]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: reveal-md-example-npm-cache
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-${{ hashFiles('**/package.json', '**/package-lock.json') }}
    - run: npm i ; npm run gh-pages
    - name: Deploy 🚀 GitHub Pages build
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: dist # The folder the action should deploy.
